package utility;

public enum TypeOfAnswer {
    OBJECTNOTEXIST,
    DUPLICATESDETECTED,
    ISNTMAX,
    ISNTMIN,
    PERMISSIONDENIED,
    SUCCESSFUL,
    SQLPROBLEM,
    EMPTYCOLLECTION,
    ALREADYREGISTERED,
    NOTMATCH;
}
